export { default as RegisterUser } from './RegisterScreens/RegisterUser'
export { default as SuccessReg } from './RegisterScreens/SuccessReg'
export { default as Login } from './Login'
export { default as Main } from './Main'
export { default as Account } from './Account'